class_name WordGenerator

const SYLLABLE_DICT = {
	"ing": 11,
	"er": 11,
	"a": 11,
	"ly": 11,
	"ed": 11,
	"i": 11,
	"es": 11,
	"re": 11,
	"tion": 11,
	"in": 11,
	"e": 11,
	"con": 11,
	"y": 11,
	"ter": 11,
	"ex": 11,
	"al": 11,
	"de": 11,
	"com": 10,
	"o": 10,
	"di": 10,
	"en": 10,
	"an": 10,
	"ty": 10,
	"ry": 10,
	"u": 10,
	"ti": 10,
	"ri": 10,
	"be": 10,
	"per": 10,
	"to": 10,
	"pro": 10,
	"ac": 10,
	"ad": 10,
	"ar": 10,
	"ers": 10,
	"ment": 10,
	"or": 10,
	"tions": 10,
	"ble": 10,
	"der": 10,
	"ma": 10,
	"na": 10,
	"si": 10,
	"un": 10,
	"at": 10,
	"dis": 10,
	"ca": 10,
	"cal": 10,
	"man": 10,
	"ap": 9,
	"po": 9,
	"sion": 9,
	"vi": 9,
	"el": 9,
	"est": 9,
	"la": 9,
	"lar": 9,
	"pa": 9,
	"ture": 9,
	"for": 9,
	"is": 9,
	"mer": 9,
	"pe": 9,
	"ra": 9,
	"so": 9,
	"ta": 9,
	"as": 9,
	"col": 9,
	"fi": 9,
	"ful": 9,
	"ger": 9,
	"low": 9,
	"ni": 9,
	"par": 9,
	"son": 9,
	"tle": 9,
	"day": 9,
	"ny": 9,
	"pen": 9,
	"pre": 9,
	"tive": 9,
	"car": 8,
	"ci": 8,
	"mo": 8,
	"on": 8,
	"ous": 8,
	"pi": 8,
	"se": 8,
	"ten": 8,
	"tor": 8,
	"ver": 8,
	"ber": 8,
	"can": 8,
	"dy": 8,
	"et": 8,
	"it": 8,
	"mu": 8,
	"no": 8,
	"ple": 8,
	"cu": 8,
	"fac": 8,
	"fer": 8,
	"gen": 8,
	"ic": 8,
	"land": 8,
	"light": 8,
	"ob": 8,
	"of": 8,
	"pos": 8,
	"tain": 8,
	"den": 8,
	"ings": 8,
	"mag": 8,
	"ments": 7,
	"set": 7,
	"some": 7,
	"sub": 7,
	"sur": 7,
	"ters": 7,
	"tu": 7,
	"af": 7,
	"au": 7,
	"cy": 7,
	"fa": 7,
	"im": 7,
	"li": 7,
	"lo": 7,
	"men": 7,
	"min": 7,
	"mon": 7,
	"op": 7,
	"out": 7,
	"rec": 7,
	"ro": 7,
	"sen": 7,
	"side": 7,
	"tal": 7,
	"tic": 7,
	"ties": 7,
	"ward": 7,
	"age": 7,
	"ba": 7,
	"but": 7,
	"cit": 7,
	"cle": 7,
	"co": 6,
	"cov": 6,
	"da": 6,
	"dif": 6,
	"ence": 6,
	"ern": 6,
	"eve": 6,
	"hap": 6,
	"ies": 6,
	"ket": 6,
	"lec": 6,
	"main": 6,
	"mar": 6,
	"mis": 6,
	"my": 6,
	"nal": 6,
	"ness": 6,
	"ning": 6,
	"n\'t": 6,
	"nu": 6,
	"oc": 6,
	"pres": 6,
	"sup": 6,
	"te": 6,
	"ted": 6,
	"tem": 6,
	"tin": 6,
	"tri": 6,
	"tro": 6,
	"up": 6,
	"va": 6,
	"ven": 6,
	"vis": 6,
	"am": 5,
	"bor": 5,
	"by": 5,
	"cat": 5,
	"cent": 5,
	"ev": 5,
	"gan": 5,
	"gle": 5,
	"head": 5,
	"high": 5,
	"il": 5,
	"lu": 5,
	"me": 5,
	"nore": 5,
	"part": 5,
	"por": 5,
	"read": 5,
	"rep": 5,
	"su": 5,
	"tend": 5,
	"ther": 5,
	"ton": 5,
	"try": 5,
	"um": 5,
	"uer": 5,
	"way": 5,
	"ate": 5,
	"bet": 5,
	"bles": 5,
	"bod": 5,
	"cap": 5,
	"cial": 5,
	"cir": 4,
	"cor": 4,
	"coun": 4,
	"cus": 4,
	"dan": 4,
	"dle": 4,
	"ef": 4,
	"end": 4,
	"ent": 4,
	"ered": 4,
	"fin": 4,
	"form": 4,
	"go": 4,
	"har": 4,
	"ish": 4,
	"lands": 4,
	"let": 4,
	"long": 4,
	"mat": 4,
	"meas": 4,
	"mem": 4,
	"mul": 4,
	"ner": 4,
	"play": 4,
	"ples": 4,
	"ply": 4,
	"port": 4,
	"press": 4,
	"sat": 4,
	"sec": 4,
	"ser": 4,
	"south": 4,
	"sun": 3,
	"the": 3,
	"ting": 3,
	"tra": 3,
	"tures": 3,
	"val": 3,
	"var": 3,
	"vid": 3,
	"wil": 3,
	"win": 3,
	"won": 3,
	"work": 3,
	"act": 3,
	"ag": 3,
	"air": 3,
	"als": 3,
	"bat": 3,
	"bi": 3,
	"cate": 3,
	"cen": 3,
	"char": 3,
	"come": 3,
	"cul": 3,
	"ders": 3,
	"east": 3,
	"fect": 3,
	"fish": 3,
	"fix": 3,
	"gi": 3,
	"grand": 3,
	"great": 3,
	"heav": 3,
	"ho": 2,
	"hunt": 2,
	"ion": 2,
	"its": 2,
	"jo": 2,
	"lat": 2,
	"lead": 2,
	"lect": 2,
	"lent": 2,
	"less": 2,
	"lin": 2,
	"mal": 2,
	"mi": 2,
	"mil": 2,
	"moth": 2,
	"near": 2,
	"nel": 2,
	"net": 2,
	"new": 2,
	"one": 2,
	"point": 2,
	"prac": 2,
	"ral": 2,
	"rect": 2,
	"ried": 2,
	"round": 2,
	"row": 2,
	"sa": 2,
	"sand": 2,
	"self": 2,
	"sent": 2,
	"ship": 2,
	"sim": 1,
	"sions": 1,
	"sis": 1,
	"sons": 1,
	"stand": 1,
	"sug": 1,
	"tel": 1,
	"tom": 1,
	"tors": 1,
	"tract": 1,
	"tray": 1,
	"us": 1,
	"vel": 1,
	"west": 1,
	"where": 1,
	"writ": 1
}
const MAX_SYLLABLES: int = 3
const PUNCTUATION_ARRAY: Array = ["_", "--", ", ", "; ", "'", "-", "... "]
const MAX_SENTENCE_LENGTH: int = 10  # must be greater than 3
const CHANCE_OF_RANDOM_PUNCTUATION: float = 0.25  # perecentage value 0.0 - 1.0
var random: RandomNumberGenerator = RandomNumberGenerator.new()


func _get_syllable() -> String:
	return SYLLABLE_DICT.keys()[random.rand_weighted(SYLLABLE_DICT.values())]


func _get_word() -> String:
	var num_syllables: int = (random.randi() % MAX_SYLLABLES) + 1
	var word: String = ""
	for syllable in range(num_syllables):
		var next_syllable: String = _get_syllable()
		word += next_syllable
	return word


func _get_punctuation() -> String:
	return PUNCTUATION_ARRAY.pick_random()


func get_sentence_array(num_words: int) -> Array:
	var sentence: Array = []
	for word_index in range(num_words):
		var next_word: String = _get_word()

		# start of sentence always capitialize + space
		if word_index == 0:
			next_word = next_word.capitalize()
			sentence.append(next_word)
			sentence.append(" ")
			continue
		# end of sentence always gets end of sentence punctuation
		elif word_index == (num_words - 1):
			sentence.append(next_word)
			sentence.append([".", "!", "?"].pick_random())
			continue
		sentence.append(next_word)
		var add_random_punctuation: bool = randf() > (1 - CHANCE_OF_RANDOM_PUNCTUATION)
		if add_random_punctuation:
			sentence.append(_get_punctuation())
		else:
			sentence.append(" ")
	return sentence


func get_paragraph_array(num_sentences: int) -> Array:
	var paragraph: Array = []
	for sentence_index in range(num_sentences):
		var sentence_length: int = randi_range(3, MAX_SENTENCE_LENGTH)
		var next_sentence: Array = get_sentence_array(sentence_length)
		paragraph.append(next_sentence)
	return paragraph


func join_sentence_to_string(token_array: Array) -> String:
	return "".join(token_array)


func join_paragraph_to_string(token_array: Array) -> String:
	var paragraph: String = ""
	for sentence in token_array:
		var sentence_string: String = "".join(sentence)
		paragraph += sentence_string
		paragraph += " "
	paragraph = paragraph.strip_edges()
	return paragraph
